jest_test
digital-go-jp/abr-geocoder pull request #172
Opened 2024-09-08 04:09 UTC by yutoshima

2024-09-08 04:14 UTC, yutoshima commented
例えば、「ｶﾝｻﾞｷﾋﾞﾙ」はこれでは変換されないという認識で大丈夫ですか？

2024-09-18 03:02 UTC, maskatsum requested changes

2024-09-18 03:02 UTC, maskatsum commented on src/usecases/geocode/services/__tests__/jis-kanji.test.ts
東京都千代田区麹町一丁目 は存在しません。ですが `jisKanji` においては、存在する場所かどうかは関係していないです。
あくまでも変換するべき漢字が期待値に変換されるかどうか、です。

`麹町` の `麹` が `糀` に変換されることを期待しているテストなので、このテストコードは必要ですので、消さないでください

2024-09-18 03:03 UTC, maskatsum commented
<img width="392" alt="Screenshot 2024-09-17 at 8 03 25 PM" src="https://github.com/user-attachments/assets/6bcee97d-5a2f-41cf-b3c4-12400bff85d2">

`main` ブランチに対してのPRではなく、`develop` ブランチに対してお願い致します。

2024-09-18 03:08 UTC, maskatsum commented
PRを作成する際に、説明を書いてくださいね。

> 例えば、「ｶﾝｻﾞｷﾋﾞﾙ」はこれでは変換されないという認識で大丈夫ですか？

これは何に対してコメントしていますか？主語を書いていただけますか？

2024-09-26 06:44 UTC, yutoshima commented
to-hiragana.tsにｶﾝｻﾞｷﾋﾞﾙのように半角濁点を入れると、テストで弾かれるのですが、それは仕様としてそうなっているのでしょうか？

2024-09-26 06:47 UTC, yutoshima commented
麹町一丁目から糀町一丁目のテストに関してですが、テストではねられるのですが、これは仕様で決まっているのでしょうか？

2024-09-27 02:39 UTC, maskatsum commented
> 麹町一丁目から糀町一丁目のテストに関してですが、テストではねられるのですが、これは仕様で決まっているのでしょうか？

develop ブランチと`feature/issue-138` で大分差があるようですが、rebaseしてもテストがはねられますか？

2024-09-27 09:52 UTC, yutoshima commented
はい
rebaseしても通らないです

2024-09-29 00:43 UTC, maskatsum commented
では、テストが通るように必要なファイルを修正してもらえますか？

2024-09-29 00:44 UTC, maskatsum commented
あと、jest.config.js と package.json は含める必要がありません。rebase すれば含まれなくなるので、rebase してください

2024-10-15 05:47 UTC, merged

2024-10-15 05:49 UTC, maskatsum commented
マージされました。ありがとうございます！