wip: try to match with koaza  #90
digital-go-jp/abr-geocoder pull request #96
Opened 2024-01-11 07:30 UTC by maskatsum

# Issue

- close #90 

# Overview

「小字」のジオコーディングを試みる

2024-01-11 07:55 UTC, maskatsum commented
<!-- Jest Coverage Comment: lint_and_build -->
## Coverage Summary

| Lines | Statements | Branches | Functions |
| --- | --- | --- | --- |
| <a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/README.md"><img alt="Coverage: 80%" src="https://img.shields.io/badge/Coverage-80%25-green.svg" /></a><br/> | 81.21% (1375/1693) | 59% (177/300) | 77.12% (209/271) |


## JUnit

| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 128 | 0 :zzz: | 0 :x: | 0 :fire: | 8.335s :stopwatch: |


<details><summary>Coverage Details (<b>80%</b>)</summary><table><tr><th>File</th><th>% Stmts</th><th>% Branch</th><th>% Funcs</th><th>% Lines</th><th>Uncovered Line #s</th></tr><tbody><tr><td><b>All files</b></td><td><b>81.21</b></td><td><b>59</b></td><td><b>77.12</b></td><td><b>80.81</b></td><td>&nbsp;</td></tr><tr><td>cli</td><td>95.29</td><td>79.16</td><td>100</td><td>95.12</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/cli/cli.ts">cli.ts</a></td><td>95.29</td><td>79.16</td><td>100</td><td>95.12</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/cli/cli.ts#L263">263</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/cli/cli.ts#L281">281</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/cli/cli.ts#L309">309</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/cli/cli.ts#L315">315</a></td></tr><tr><td>controller/download</td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/download/download-dataset-result.ts">download-dataset-result.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/download/download-dataset.ts">download-dataset.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>controller/download/process</td><td>75.6</td><td>73.91</td><td>62.5</td><td>74.57</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/download/process/download-process.ts">download-process.ts</a></td><td>23.52</td><td>100</td><td>0</td><td>18.75</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/download/process/download-process.ts#L46-L77">46&ndash;77</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/download/process/extract-dataset-process.ts">extract-dataset-process.ts</a></td><td>50</td><td>100</td><td>0</td><td>45.45</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/download/process/extract-dataset-process.ts#L45-L60">45&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/download/process/load-dataset-history.ts">load-dataset-history.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/download/process/load-dataset-process.ts">load-dataset-process.ts</a></td><td>87.2</td><td>73.91</td><td>88.88</td><td>86.9</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/download/process/load-dataset-process.ts#L77">77</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/download/process/load-dataset-process.ts#L100-L102">100&ndash;102</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/download/process/load-dataset-process.ts#L131-L132">131&ndash;132</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/download/process/load-dataset-process.ts#L155-L158">155&ndash;158</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/download/process/load-dataset-process.ts#L216">216</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/download/process/load-dataset-process.ts#L226">226</a></td></tr><tr><td>controller/geocode</td><td>90.1</td><td>66.66</td><td>78.33</td><td>90.03</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/geocode/geocode.ts">geocode.ts</a></td><td>81.08</td><td>41.66</td><td>100</td><td>80.55</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/geocode/geocode.ts#L87-L106">87&ndash;106</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/geocode/geocode.ts#L116">116</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/geocode/step1-transform.ts">step1-transform.ts</a></td><td>95.23</td><td>100</td><td>85.71</td><td>95.23</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/geocode/step1-transform.ts#L105">105</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/geocode/step2-transform.ts">step2-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/geocode/step3-transform.ts">step3-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/geocode/step3a-transform.ts">step3a-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/geocode/step3b-transform.ts">step3b-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/geocode/step3final-transform.ts">step3final-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/geocode/step4-transform.ts">step4-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/85c2746dd1fc8c5327ffed3731fe8b1ae1a90f15/./src/controller/geocode/step5-transform.ts">step5-transform.ts</a></td><td>87.8</td><td>100</td><td>61.53</td><td>87.8</td><td><a href="h [...]

2024-01-11 08:23 UTC, maskatsum commented
<!-- Jest Coverage Comment: lint_and_build -->
## Coverage Summary

| Lines | Statements | Branches | Functions |
| --- | --- | --- | --- |
| <a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/README.md"><img alt="Coverage: 81%" src="https://img.shields.io/badge/Coverage-81%25-green.svg" /></a><br/> | 81.98% (1388/1693) | 59.33% (178/300) | 78.22% (212/271) |


## JUnit

| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 129 | 0 :zzz: | 0 :x: | 0 :fire: | 8.223s :stopwatch: |


<details><summary>Coverage Details (<b>81%</b>)</summary><table><tr><th>File</th><th>% Stmts</th><th>% Branch</th><th>% Funcs</th><th>% Lines</th><th>Uncovered Line #s</th></tr><tbody><tr><td><b>All files</b></td><td><b>81.98</b></td><td><b>59.33</b></td><td><b>78.22</b></td><td><b>81.6</b></td><td>&nbsp;</td></tr><tr><td>cli</td><td>95.29</td><td>79.16</td><td>100</td><td>95.12</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/cli/cli.ts">cli.ts</a></td><td>95.29</td><td>79.16</td><td>100</td><td>95.12</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/cli/cli.ts#L263">263</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/cli/cli.ts#L281">281</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/cli/cli.ts#L309">309</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/cli/cli.ts#L315">315</a></td></tr><tr><td>controller/download</td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/download/download-dataset-result.ts">download-dataset-result.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/download/download-dataset.ts">download-dataset.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>controller/download/process</td><td>75.6</td><td>73.91</td><td>62.5</td><td>74.57</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/download/process/download-process.ts">download-process.ts</a></td><td>23.52</td><td>100</td><td>0</td><td>18.75</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/download/process/download-process.ts#L46-L77">46&ndash;77</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/download/process/extract-dataset-process.ts">extract-dataset-process.ts</a></td><td>50</td><td>100</td><td>0</td><td>45.45</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/download/process/extract-dataset-process.ts#L45-L60">45&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/download/process/load-dataset-history.ts">load-dataset-history.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/download/process/load-dataset-process.ts">load-dataset-process.ts</a></td><td>87.2</td><td>73.91</td><td>88.88</td><td>86.9</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/download/process/load-dataset-process.ts#L77">77</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/download/process/load-dataset-process.ts#L100-L102">100&ndash;102</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/download/process/load-dataset-process.ts#L131-L132">131&ndash;132</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/download/process/load-dataset-process.ts#L155-L158">155&ndash;158</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/download/process/load-dataset-process.ts#L216">216</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/download/process/load-dataset-process.ts#L226">226</a></td></tr><tr><td>controller/geocode</td><td>90.1</td><td>66.66</td><td>78.33</td><td>90.03</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/geocode/geocode.ts">geocode.ts</a></td><td>81.08</td><td>41.66</td><td>100</td><td>80.55</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/geocode/geocode.ts#L87-L106">87&ndash;106</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/geocode/geocode.ts#L116">116</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/geocode/step1-transform.ts">step1-transform.ts</a></td><td>95.23</td><td>100</td><td>85.71</td><td>95.23</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/geocode/step1-transform.ts#L105">105</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/geocode/step2-transform.ts">step2-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/geocode/step3-transform.ts">step3-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/geocode/step3a-transform.ts">step3a-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/geocode/step3b-transform.ts">step3b-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/geocode/step3final-transform.ts">step3final-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/geocode/step4-transform.ts">step4-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/159ca92e0c6c1aa9006515bd3658029d25ef4346/./src/controller/geocode/step5-transform.ts">step5-transform.ts</a></td><td>87.8</td><td>100</td><td>61.53</td><td>87.8</td><td><a hr [...]

2024-01-11 08:26 UTC, maskatsum commented
たぶん良さそうだけど、もう少しテストケースを作ってみます

2024-01-12 07:36 UTC, maskatsum commented
<!-- Jest Coverage Comment: lint_and_build -->
## Coverage Summary

| Lines | Statements | Branches | Functions |
| --- | --- | --- | --- |
| <a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/README.md"><img alt="Coverage: 81%" src="https://img.shields.io/badge/Coverage-81%25-green.svg" /></a><br/> | 82.16% (1391/1693) | 59.66% (179/300) | 78.22% (212/271) |


## JUnit

| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 130 | 0 :zzz: | 0 :x: | 0 :fire: | 8.188s :stopwatch: |


<details><summary>Coverage Details (<b>81%</b>)</summary><table><tr><th>File</th><th>% Stmts</th><th>% Branch</th><th>% Funcs</th><th>% Lines</th><th>Uncovered Line #s</th></tr><tbody><tr><td><b>All files</b></td><td><b>82.16</b></td><td><b>59.66</b></td><td><b>78.22</b></td><td><b>81.78</b></td><td>&nbsp;</td></tr><tr><td>cli</td><td>95.29</td><td>79.16</td><td>100</td><td>95.12</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/cli/cli.ts">cli.ts</a></td><td>95.29</td><td>79.16</td><td>100</td><td>95.12</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/cli/cli.ts#L263">263</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/cli/cli.ts#L281">281</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/cli/cli.ts#L309">309</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/cli/cli.ts#L315">315</a></td></tr><tr><td>controller/download</td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/download/download-dataset-result.ts">download-dataset-result.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/download/download-dataset.ts">download-dataset.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>controller/download/process</td><td>75.6</td><td>73.91</td><td>62.5</td><td>74.57</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/download/process/download-process.ts">download-process.ts</a></td><td>23.52</td><td>100</td><td>0</td><td>18.75</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/download/process/download-process.ts#L46-L77">46&ndash;77</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/download/process/extract-dataset-process.ts">extract-dataset-process.ts</a></td><td>50</td><td>100</td><td>0</td><td>45.45</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/download/process/extract-dataset-process.ts#L45-L60">45&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/download/process/load-dataset-history.ts">load-dataset-history.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/download/process/load-dataset-process.ts">load-dataset-process.ts</a></td><td>87.2</td><td>73.91</td><td>88.88</td><td>86.9</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/download/process/load-dataset-process.ts#L77">77</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/download/process/load-dataset-process.ts#L100-L102">100&ndash;102</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/download/process/load-dataset-process.ts#L131-L132">131&ndash;132</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/download/process/load-dataset-process.ts#L155-L158">155&ndash;158</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/download/process/load-dataset-process.ts#L216">216</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/download/process/load-dataset-process.ts#L226">226</a></td></tr><tr><td>controller/geocode</td><td>90.1</td><td>66.66</td><td>78.33</td><td>90.03</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/geocode/geocode.ts">geocode.ts</a></td><td>81.08</td><td>41.66</td><td>100</td><td>80.55</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/geocode/geocode.ts#L87-L106">87&ndash;106</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/geocode/geocode.ts#L116">116</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/geocode/step1-transform.ts">step1-transform.ts</a></td><td>95.23</td><td>100</td><td>85.71</td><td>95.23</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/geocode/step1-transform.ts#L105">105</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/geocode/step2-transform.ts">step2-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/geocode/step3-transform.ts">step3-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/geocode/step3a-transform.ts">step3a-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/geocode/step3b-transform.ts">step3b-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/geocode/step3final-transform.ts">step3final-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/geocode/step4-transform.ts">step4-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/0a9b43a3cee3a070da8d1307a7f4f7154f0de81d/./src/controller/geocode/step5-transform.ts">step5-transform.ts</a></td><td>87.8</td><td>100</td><td>61.53</td><td>87.8</td><td><a h [...]

2024-01-12 07:46 UTC, maskatsum commented
## `八戸市尻内町字下根市25-2` のクエリ

```json
[
  {
    "query": {
      "input": "八戸市尻内町字下根市25-2"
    },
    "result": {
      "output": "青森県八戸市大字尻内町字下根市25-2",
      "prefecture": "青森県",
      "match_level": 4,
      "city": "八戸市",
      "town": "大字尻内町",
      "town_id": "0033105",
      "lg_code": "022039",
      "other": "25-2",
      "lat": null,
      "lon": null,
      "addr1": "字下根市"
    }
  }
]
```

## `いわき市山玉町脇川2 いわき市役所 水道局 山玉浄水場` のクエリ
 
```json
[
  {
    "query": {
      "input": "いわき市山玉町脇川2 いわき市役所 水道局 山玉浄水場"
    },
    "result": {
      "output": "福島県いわき市山玉町脇川2 いわき市役所 水道局 山玉浄水場",
      "prefecture": "福島県",
      "match_level": 4,
      "city": "いわき市",
      "town": "山玉町",
      "town_id": "0113116",
      "lg_code": "072044",
      "other": "2 いわき市役所 水道局 山玉浄水場",
      "lat": 36.901176,
      "lon": 140.725118,
      "addr1": "脇川"
    }
  }
]
```

## `盛岡市飯岡新田４地割１００１ 河南自治公民館` のクエリ

```json
[
  {
    "query": {
      "input": "盛岡市飯岡新田４地割１００１ 河南自治公民館"
    },
    "result": {
      "output": "岩手県盛岡市飯岡新田4地割1001 河南自治公民館",
      "prefecture": "岩手県",
      "match_level": 4,
      "city": "盛岡市",
      "town": "飯岡新田",
      "town_id": "0007105",
      "lg_code": "032018",
      "other": "1001 河南自治公民館",
      "lat": null,
      "lon": null,
      "addr1": "4地割"
    }
  }
]
```

2024-01-13 00:20 UTC, koswatana commented
- 小字は町字の一部なのでv1のマッチングレベルは`3`
![image](https://github.com/digital-go-jp/abr-geocoder/assets/85000484/cc24a708-b037-4716-b3cb-a25a7988f5af)
- そのため小字は`addr1`ではなく`town`

2024-01-13 01:20 UTC, maskatsum commented
この図はどこで参照することができますか？

2024-01-13 01:34 UTC, maskatsum commented
https://www.digital.go.jp/assets/contents/node/basic_page/field_ref_resources/3d996df3-f87c-4439-b474-c0fbbf3ddad8/d010b173/20220422_policies_base_registry_manual_01.pdf

分かりました。これのpage5 ですね。

2024-01-13 02:06 UTC, maskatsum commented
<!-- Jest Coverage Comment: lint_and_build -->
## Coverage Summary

| Lines | Statements | Branches | Functions |
| --- | --- | --- | --- |
| <a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/README.md"><img alt="Coverage: 81%" src="https://img.shields.io/badge/Coverage-81%25-green.svg" /></a><br/> | 82.15% (1390/1692) | 59.66% (179/300) | 78.22% (212/271) |


## JUnit

| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 130 | 0 :zzz: | 0 :x: | 0 :fire: | 9.313s :stopwatch: |


<details><summary>Coverage Details (<b>81%</b>)</summary><table><tr><th>File</th><th>% Stmts</th><th>% Branch</th><th>% Funcs</th><th>% Lines</th><th>Uncovered Line #s</th></tr><tbody><tr><td><b>All files</b></td><td><b>82.15</b></td><td><b>59.66</b></td><td><b>78.22</b></td><td><b>81.77</b></td><td>&nbsp;</td></tr><tr><td>cli</td><td>95.29</td><td>79.16</td><td>100</td><td>95.12</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/cli/cli.ts">cli.ts</a></td><td>95.29</td><td>79.16</td><td>100</td><td>95.12</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/cli/cli.ts#L263">263</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/cli/cli.ts#L281">281</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/cli/cli.ts#L309">309</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/cli/cli.ts#L315">315</a></td></tr><tr><td>controller/download</td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/download/download-dataset-result.ts">download-dataset-result.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/download/download-dataset.ts">download-dataset.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>controller/download/process</td><td>75.6</td><td>73.91</td><td>62.5</td><td>74.57</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/download/process/download-process.ts">download-process.ts</a></td><td>23.52</td><td>100</td><td>0</td><td>18.75</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/download/process/download-process.ts#L46-L77">46&ndash;77</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/download/process/extract-dataset-process.ts">extract-dataset-process.ts</a></td><td>50</td><td>100</td><td>0</td><td>45.45</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/download/process/extract-dataset-process.ts#L45-L60">45&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/download/process/load-dataset-history.ts">load-dataset-history.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/download/process/load-dataset-process.ts">load-dataset-process.ts</a></td><td>87.2</td><td>73.91</td><td>88.88</td><td>86.9</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/download/process/load-dataset-process.ts#L77">77</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/download/process/load-dataset-process.ts#L100-L102">100&ndash;102</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/download/process/load-dataset-process.ts#L131-L132">131&ndash;132</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/download/process/load-dataset-process.ts#L155-L158">155&ndash;158</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/download/process/load-dataset-process.ts#L216">216</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/download/process/load-dataset-process.ts#L226">226</a></td></tr><tr><td>controller/geocode</td><td>90.1</td><td>66.66</td><td>78.33</td><td>90.03</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/geocode/geocode.ts">geocode.ts</a></td><td>81.08</td><td>41.66</td><td>100</td><td>80.55</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/geocode/geocode.ts#L87-L106">87&ndash;106</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/geocode/geocode.ts#L116">116</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/geocode/step1-transform.ts">step1-transform.ts</a></td><td>95.23</td><td>100</td><td>85.71</td><td>95.23</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/geocode/step1-transform.ts#L105">105</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/geocode/step2-transform.ts">step2-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/geocode/step3-transform.ts">step3-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/geocode/step3a-transform.ts">step3a-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/geocode/step3b-transform.ts">step3b-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/geocode/step3final-transform.ts">step3final-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/geocode/step4-transform.ts">step4-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/82bb49c130a503aeef664ad8e0729fa8d2bb8836/./src/controller/geocode/step5-transform.ts">step5-transform.ts</a></td><td>87.8</td><td>100</td><td>61.53</td><td>87.8</td><td><a h [...]

2024-01-13 02:06 UTC, maskatsum commented
@koswatana 修正しました〜

2024-01-13 04:49 UTC, maskatsum commented
<!-- Jest Coverage Comment: lint_and_build -->
## Coverage Summary

| Lines | Statements | Branches | Functions |
| --- | --- | --- | --- |
| <a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/README.md"><img alt="Coverage: 81%" src="https://img.shields.io/badge/Coverage-81%25-green.svg" /></a><br/> | 82.14% (1394/1697) | 59.46% (179/301) | 78.3% (213/272) |


## JUnit

| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 130 | 0 :zzz: | 0 :x: | 0 :fire: | 8.877s :stopwatch: |


<details><summary>Coverage Details (<b>81%</b>)</summary><table><tr><th>File</th><th>% Stmts</th><th>% Branch</th><th>% Funcs</th><th>% Lines</th><th>Uncovered Line #s</th></tr><tbody><tr><td><b>All files</b></td><td><b>82.14</b></td><td><b>59.46</b></td><td><b>78.3</b></td><td><b>81.76</b></td><td>&nbsp;</td></tr><tr><td>cli</td><td>95.29</td><td>79.16</td><td>100</td><td>95.12</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/cli/cli.ts">cli.ts</a></td><td>95.29</td><td>79.16</td><td>100</td><td>95.12</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/cli/cli.ts#L263">263</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/cli/cli.ts#L281">281</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/cli/cli.ts#L309">309</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/cli/cli.ts#L315">315</a></td></tr><tr><td>controller/download</td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/download/download-dataset-result.ts">download-dataset-result.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/download/download-dataset.ts">download-dataset.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>controller/download/process</td><td>75.6</td><td>73.91</td><td>62.5</td><td>74.57</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/download/process/download-process.ts">download-process.ts</a></td><td>23.52</td><td>100</td><td>0</td><td>18.75</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/download/process/download-process.ts#L46-L77">46&ndash;77</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/download/process/extract-dataset-process.ts">extract-dataset-process.ts</a></td><td>50</td><td>100</td><td>0</td><td>45.45</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/download/process/extract-dataset-process.ts#L45-L60">45&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/download/process/load-dataset-history.ts">load-dataset-history.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/download/process/load-dataset-process.ts">load-dataset-process.ts</a></td><td>87.2</td><td>73.91</td><td>88.88</td><td>86.9</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/download/process/load-dataset-process.ts#L77">77</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/download/process/load-dataset-process.ts#L100-L102">100&ndash;102</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/download/process/load-dataset-process.ts#L131-L132">131&ndash;132</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/download/process/load-dataset-process.ts#L155-L158">155&ndash;158</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/download/process/load-dataset-process.ts#L216">216</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/download/process/load-dataset-process.ts#L226">226</a></td></tr><tr><td>controller/geocode</td><td>90.1</td><td>66.66</td><td>78.33</td><td>90.03</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/geocode/geocode.ts">geocode.ts</a></td><td>81.08</td><td>41.66</td><td>100</td><td>80.55</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/geocode/geocode.ts#L87-L106">87&ndash;106</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/geocode/geocode.ts#L116">116</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/geocode/step1-transform.ts">step1-transform.ts</a></td><td>95.23</td><td>100</td><td>85.71</td><td>95.23</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/geocode/step1-transform.ts#L105">105</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/geocode/step2-transform.ts">step2-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/geocode/step3-transform.ts">step3-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/geocode/step3a-transform.ts">step3a-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/geocode/step3b-transform.ts">step3b-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/geocode/step3final-transform.ts">step3final-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/geocode/step4-transform.ts">step4-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/76e6cd3aa1c8ac7acf7ddab8282796c54443874c/./src/controller/geocode/step5-transform.ts">step5-transform.ts</a></td><td>87.8</td><td>100</td><td>61.53</td><td>87.8</td><td><a hre [...]

2024-01-19 04:19 UTC, koswatana commented
# `福島県いわき市山玉町脇川`のクエリ OK
```
# echo "福島県いわき市山玉町脇川" | npx ts-node src/cli/cli.ts -f json - | jq .
[
  {
    "query": {
      "input": "福島県いわき市山玉町脇川"
    },
    "result": {
      "output": "福島県いわき市山玉町脇川",
      "prefecture": "福島県",
      "match_level": 3,
      "city": "いわき市",
      "town": "山玉町脇川",
      "town_id": "0113116",
      "lg_code": "072044",
      "other": "",
      "lat": 36.901176,
      "lon": 140.725118
    }
  }
]
```

2024-01-19 17:53 UTC, maskatsum commented
ありがとうございます。私の方でも別ケースに対応できていない件を気づいていて、ロジックを補強中なので、もう少しお待ち下さいー

2024-01-20 08:22 UTC, maskatsum commented
<!-- Jest Coverage Comment: lint_and_build -->
## Coverage Summary

| Lines | Statements | Branches | Functions |
| --- | --- | --- | --- |
| <a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/README.md"><img alt="Coverage: 82%" src="https://img.shields.io/badge/Coverage-82%25-green.svg" /></a><br/> | 82.5% (1457/1766) | 60.45% (185/306) | 78.98% (218/276) |


## JUnit

| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 133 | 0 :zzz: | 0 :x: | 0 :fire: | 8.926s :stopwatch: |


<details><summary>Coverage Details (<b>82%</b>)</summary><table><tr><th>File</th><th>% Stmts</th><th>% Branch</th><th>% Funcs</th><th>% Lines</th><th>Uncovered Line #s</th></tr><tbody><tr><td><b>All files</b></td><td><b>82.5</b></td><td><b>60.45</b></td><td><b>78.98</b></td><td><b>82.14</b></td><td>&nbsp;</td></tr><tr><td>cli</td><td>95.29</td><td>79.16</td><td>100</td><td>95.12</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/cli/cli.ts">cli.ts</a></td><td>95.29</td><td>79.16</td><td>100</td><td>95.12</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/cli/cli.ts#L263">263</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/cli/cli.ts#L281">281</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/cli/cli.ts#L309">309</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/cli/cli.ts#L315">315</a></td></tr><tr><td>controller/download</td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/download/download-dataset-result.ts">download-dataset-result.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/download/download-dataset.ts">download-dataset.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>controller/download/process</td><td>75.6</td><td>73.91</td><td>62.5</td><td>74.57</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/download/process/download-process.ts">download-process.ts</a></td><td>23.52</td><td>100</td><td>0</td><td>18.75</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/download/process/download-process.ts#L46-L77">46&ndash;77</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/download/process/extract-dataset-process.ts">extract-dataset-process.ts</a></td><td>50</td><td>100</td><td>0</td><td>45.45</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/download/process/extract-dataset-process.ts#L45-L60">45&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/download/process/load-dataset-history.ts">load-dataset-history.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/download/process/load-dataset-process.ts">load-dataset-process.ts</a></td><td>87.2</td><td>73.91</td><td>88.88</td><td>86.9</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/download/process/load-dataset-process.ts#L77">77</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/download/process/load-dataset-process.ts#L100-L102">100&ndash;102</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/download/process/load-dataset-process.ts#L131-L132">131&ndash;132</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/download/process/load-dataset-process.ts#L155-L158">155&ndash;158</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/download/process/load-dataset-process.ts#L216">216</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/download/process/load-dataset-process.ts#L226">226</a></td></tr><tr><td>controller/geocode</td><td>90.25</td><td>64.28</td><td>78.94</td><td>90.18</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/geocode/geocode.ts">geocode.ts</a></td><td>81.08</td><td>41.66</td><td>100</td><td>80.55</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/geocode/geocode.ts#L87-L106">87&ndash;106</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/geocode/geocode.ts#L116">116</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/geocode/step1-transform.ts">step1-transform.ts</a></td><td>95.23</td><td>100</td><td>85.71</td><td>95.23</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/geocode/step1-transform.ts#L105">105</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/geocode/step2-transform.ts">step2-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/geocode/step3-transform.ts">step3-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/geocode/step3a-transform.ts">step3a-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/geocode/step3b-transform.ts">step3b-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/geocode/step3final-transform.ts">step3final-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/geocode/step4-transform.ts">step4-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/5a1d8ca61d8a701abda0af1151ae7770ad50a493/./src/controller/geocode/step5-transform.ts">step5-transform.ts</a></td><td>86.48</td><td>100</td><td>54.54</td><td>86.48</td><td><a  [...]

2024-01-20 08:47 UTC, maskatsum commented
だいぶ改善しました。字を含む住所以外も精度を向上させています。

| input                                  | output                                 | match_level | lg_code | prefecture | city     | town       | town_id | block | block_id | addr1 | addr1_id | addr2 | addr2_id | other                 | lat          | lon                |
|----------------------------------------|----------------------------------------|-------------|---------|------------|----------|------------|---------|-------|----------|-------|----------|-------|----------|-----------------------|--------------|--------------------|
| "東京都千代田区紀尾井町1丁目3番地"                    | "東京都千代田区紀尾井町1-3"                       | 8           | 131016  | 東京都        | 千代田区     | 紀尾井町       | 0056000 | 1     | 001      | 3     | 003      |       |          |                       | 35.679107172 | 139.736394597      |
| "東京都千代田区紀尾井町1-3　東京ガーデンテラス紀尾井町 19階、20階" | "東京都千代田区紀尾井町1-3 東京ガーデンテラス紀尾井町 19階、20階" | 8           | 131016  | 東京都        | 千代田区     | 紀尾井町       | 0056000 | 1     | 001      | 3     | 003      |       |          | 東京ガーデンテラス紀尾井町 19階、20階 | 35.679107172 | 139.736394597      |
| "東京都千代田区紀尾井町1"                         | "東京都千代田区紀尾井町1"                         | 7           | 131016  | 東京都        | 千代田区     | 紀尾井町       | 0056000 | 1     | 001      |       |          |       |          |                       | 35.679921    | 139.737183         |
| "東京都町田市森野2-2-22"                       | "東京都町田市森野二丁目2-22"                      | 8           | 132098  | 東京都        | 町田市      | 森野二丁目      | 0006002 | 2     | 002      | 22    | 022      |       |          |                       | 35.54703962  | 139.4381441        |
| "町田市森野2-2-22"                          | "東京都町田市森野二丁目2-22"                      | 8           | 132098  | 東京都        | 町田市      | 森野二丁目      | 0006002 | 2     | 002      | 22    | 022      |       |          |                       | 35.54703962  | 139.4381441        |
| "東京都府中市宮西町二丁目二十四番地"                    | "東京都府中市宮西町二丁目244"                      | 7           | 132063  | 東京都        | 府中市      | 宮西町二丁目     | 0015002 | 24    | 024      |       |          |       |          | 4                     | 35.668859    | 139.477769         |
| "八戸市尻内町字下根市25-2"                       | "青森県八戸市大字尻内町字下根市25-2"                  | 3           | 022039  | 青森県        | 八戸市      | 大字尻内町字下根市  | 0033105 | 25    |          | 2     |          |       |          |                       |              |                    |
| "青森県八戸市内丸一丁目1番1号"                      | "青森県八戸市内丸一丁目1-1"                       | 8           | 022039  | 青森県        | 八戸市      | 内丸一丁目      | 0005001 | 1     | 001      | 1     | 001      |       |          |                       | 40.511864203 | 141.490001642      |
| "与那国町字与那国129"                          | "沖縄県八重山郡与那国町字与那国129"                   | 3           | 473821  | 沖縄県        | 八重山郡与那国町 | 字与那国       | 0001000 | 129   |          |       |          |       |          |                       | 24.455925    | 122.98767800000002 |
| "八重山郡与那国町字与那国129"                      | "沖縄県八重山郡与那国町字与那国129"                   | 3           | 473821  | 沖縄県        | 八重山郡与那国町 | 字与那国       | 0001000 | 129   |          |       |          |       |          |                       | 24.455925    | 122.98767800000002 |
| "沖縄県八重山郡与那国町字与那国129"                   | "沖縄県八重山郡与那国町字与那国129"                   | 3           | 473821  | 沖縄県        | 八重山郡与那国町 | 字与那国       | 0001000 | 129   |          |       |          |       |          |                       | 24.455925    | 122.98767800000002 |
| "宮城県登米市迫町佐沼字中江二丁目6番地1"                 | "宮城県登米市迫町佐沼字中江2丁目6-1"                  | 3           | 042129  | 宮城県        | 登米市      | 迫町佐沼       | 0318000 |       |          |       |          |       |          | 字中江2丁目6-1             | 38.691871    | 141.201558         |
| "登米市迫町佐沼字中江2-6-1"                      | "宮城県登米市迫町佐沼字中江2丁目6-1"                  | 7           | 042129  | 宮城県        | 登米市      | 迫町佐沼字中江2丁目 | 0318147 | 6     | 006      |       |          |       |          | 1                     | 38.691612    | 141.188849         |
| "盛岡市飯岡新田４地割１００１ 河南自治公民館"               | "岩手県盛岡市飯岡新田4地割1001 河南自治公民館"            | 3           | 032018  | 岩手県        | 盛岡市      | 飯岡新田4地割    | 0007105 | 1001  |          |       |          |       |          | 河南自治公民館               |              |                    |
| "福島県いわき市山玉町脇川"                         | "福島県いわき市山玉町脇川"                         | 3           | 072044  | 福島県        | いわき市     | 山玉町脇川      | 0113116 |       |          |       |          |       |          |                       | 36.901176    | 140.725118         |
| "いわき市山玉町脇川2 いわき市役所 水道局 山玉浄水場"          | "福島県いわき市山玉町脇川2 いわき市役所 水道局 山玉浄水場"       | 3           | 072044  | 福島県        | いわき市     | 山玉町脇川      | 0113116 | 2     |          |       |          |       |          | いわき市役所 水道局 山玉浄水場      | 36.901176    | 140.725118         |
| "八幡市八幡園内75"                            | "京都府八幡市八幡園内75"                         | 3           | 262102  | 京都府        | 八幡市      | 八幡園内       | 0302000 | 75    |          |       |          |       |          |                       | 34.877027    | 135.708529         |
| "八幡市八幡高畑1番地の1"                         | "京都府八幡市八幡高畑1-1"                        | 3           | 262102  | 京都府        | 八幡市      | 八幡高畑       | 0303000 | 1     |          | 1     |          |       |          |                       | 34.874458    | 135.708306         |
| "京都府八幡市八幡三本橋59番地の9"                    | "京都府八幡市八幡三本橋59-9"                      | 3           | 262102  | 京都府        | 八幡市      | 八幡三本橋      | 0290000 | 59    |          | 9     |          |       |          |                       | 34.877064    | 135.706143         |
| "山形県山形市旅篭町2丁目3番25号"                    | "山形県山形市旅篭町二丁目3-25"                     | 8           | 062014  | 山形県        | 山形市      | 旅篭町二丁目     | 0247002 | 3     | 003      | 25    | 025      |       |          |                       | 38.255246956 | 140.340220244      |
| "山形市旅篭町二丁目3番25号"                       | "山形県山形市旅篭町二丁目3-25"                     | 8           | 062014  | 山形県        | 山形市      | 旅篭町二丁目     | 0247002 | 3     | 003      | 25    | 025      |       |          |                       | 38.255246956 | 140.340220244      |
| "鹿児島県大島郡与論町茶花1418-1"                   | "鹿児島県大島郡与論町大字茶花1418-1"                 | 3           | 465356  | 鹿児島県       | 大島郡与論町   | 大字茶花       | 0002000 | 1418  |          | 1     |          |       |          |                       | 27.048143    | 128.419765         |
| "石川県輪島市二ツ屋町2字29"                       | "石川県輪島市二ツ屋町2字29"                       | 3           | 172049  | 石川県        | 輪島市      | 二ツ屋町       | 0051000 | 2     |          |       |          |       |          | 字29                   | 37.389941    | 136.899356         |

2024-01-20 08:52 UTC, maskatsum commented
<!-- Jest Coverage Comment: lint_and_build -->
## Coverage Summary

| Lines | Statements | Branches | Functions |
| --- | --- | --- | --- |
| <a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/README.md"><img alt="Coverage: 82%" src="https://img.shields.io/badge/Coverage-82%25-green.svg" /></a><br/> | 82.5% (1457/1766) | 60.45% (185/306) | 78.98% (218/276) |


## JUnit

| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 133 | 0 :zzz: | 0 :x: | 0 :fire: | 8.681s :stopwatch: |


<details><summary>Coverage Details (<b>82%</b>)</summary><table><tr><th>File</th><th>% Stmts</th><th>% Branch</th><th>% Funcs</th><th>% Lines</th><th>Uncovered Line #s</th></tr><tbody><tr><td><b>All files</b></td><td><b>82.5</b></td><td><b>60.45</b></td><td><b>78.98</b></td><td><b>82.14</b></td><td>&nbsp;</td></tr><tr><td>cli</td><td>95.29</td><td>79.16</td><td>100</td><td>95.12</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/cli/cli.ts">cli.ts</a></td><td>95.29</td><td>79.16</td><td>100</td><td>95.12</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/cli/cli.ts#L263">263</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/cli/cli.ts#L281">281</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/cli/cli.ts#L309">309</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/cli/cli.ts#L315">315</a></td></tr><tr><td>controller/download</td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/download/download-dataset-result.ts">download-dataset-result.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/download/download-dataset.ts">download-dataset.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>controller/download/process</td><td>75.6</td><td>73.91</td><td>62.5</td><td>74.57</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/download/process/download-process.ts">download-process.ts</a></td><td>23.52</td><td>100</td><td>0</td><td>18.75</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/download/process/download-process.ts#L46-L77">46&ndash;77</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/download/process/extract-dataset-process.ts">extract-dataset-process.ts</a></td><td>50</td><td>100</td><td>0</td><td>45.45</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/download/process/extract-dataset-process.ts#L45-L60">45&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/download/process/load-dataset-history.ts">load-dataset-history.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/download/process/load-dataset-process.ts">load-dataset-process.ts</a></td><td>87.2</td><td>73.91</td><td>88.88</td><td>86.9</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/download/process/load-dataset-process.ts#L77">77</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/download/process/load-dataset-process.ts#L100-L102">100&ndash;102</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/download/process/load-dataset-process.ts#L131-L132">131&ndash;132</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/download/process/load-dataset-process.ts#L155-L158">155&ndash;158</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/download/process/load-dataset-process.ts#L216">216</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/download/process/load-dataset-process.ts#L226">226</a></td></tr><tr><td>controller/geocode</td><td>90.25</td><td>64.28</td><td>78.94</td><td>90.18</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/geocode/geocode.ts">geocode.ts</a></td><td>81.08</td><td>41.66</td><td>100</td><td>80.55</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/geocode/geocode.ts#L87-L106">87&ndash;106</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/geocode/geocode.ts#L116">116</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/geocode/step1-transform.ts">step1-transform.ts</a></td><td>95.23</td><td>100</td><td>85.71</td><td>95.23</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/geocode/step1-transform.ts#L105">105</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/geocode/step2-transform.ts">step2-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/geocode/step3-transform.ts">step3-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/geocode/step3a-transform.ts">step3a-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/geocode/step3b-transform.ts">step3b-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/geocode/step3final-transform.ts">step3final-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/geocode/step4-transform.ts">step4-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/3585bdc02f99d8b82c5adad6bec22a83758c4194/./src/controller/geocode/step5-transform.ts">step5-transform.ts</a></td><td>86.48</td><td>100</td><td>54.54</td><td>86.48</td><td><a  [...]

2024-01-20 15:12 UTC, koswatana commented
- 以下のSQLで小字のテストデータを作成
```
SELECT 
  pref_name,
  county_name,
  city_name,
  od_city_name,
  oaza_town_name,
  chome_name,
  koaza_name 
FROM (
  SELECT 
    *,
    ROW_NUMBER() OVER (PARTITION BY lg_code ORDER BY town_id) as row_num
  FROM 
    town 
  WHERE 
    koaza_name != ''
) as subquery
WHERE 
  row_num = 1;
```

- 作成した小字のテストデータ 1571件
[koaza.txt](https://github.com/digital-go-jp/abr-geocoder/files/13998348/koaza.txt)

```
# npx ts-node src/cli/cli.ts -f csv ./koaza.txt ./koaza_result.txt 
```

- 結果
  -  マッチングレベル3：157件
  -  マッチングレベル2：1416件
[koaza_result.txt](https://github.com/digital-go-jp/abr-geocoder/files/13998349/koaza_result.txt)

2024-01-20 15:19 UTC, koswatana commented
`MatchLevel.RESIDENTIAL_DETAIL,` 個人的には数字のまま方がわかりやすいのですがどうですかね？

2024-01-20 23:04 UTC, maskatsum commented
どうもありがとうございます。

＞　MatchLevel.RESIDENTIAL_DETAIL, 個人的には数字のまま方がわかりやすいのですがどうですかね？

まず、この質問から回答しますね。
何かの意味を持つ数字が直接書いてあるような使い方をしている数字のことを「マジックナンバー」と言います。

例えば下記コード (v1.0の人が書いたコード) にある `indexCols: 2` とは、何を意味しているか分かりますか？
https://github.com/digital-go-jp/abr-geocoder/blob/a42a079c2e2b9535e5cdd30d009454cddbbca90c/src/downloader.ts#L277-L280

ここで分かるのは、「何かのインデックスのカラム番号が2らしい」ということだけです。
続く `stmt: db.prepare('UPDATE "town" SET "代表点_経度" = ?, "代表点_緯度" = ? WHERE "code" = ? AND "town_id" = ?'),` の部分で、`?` に値が入ってくることは分かりますが、4つもあります。
`indexCols: [1,2,3,4]` みたいになっていれば、まだ「ああ、ここに入ってくるのかな」とも想像が付きますが、`indexCols: 2` は1つだけです。

つまりここでは「`indexCols: 2` の `2` は何を意味しているのかわからない」ということになります。

**何だか分からないけど機能する数字** のことを「マジックナンバー」と言います。
このマジックナンバーの意味を知るためには、コードを読まないとなりません（他人のコードを読むのは、物凄く労力と時間がかかります）。

--------

これがもし`CSV_FILE.COLS_TOWN_ID` となっていたらどうでしょうか。
```
    'town_pos': {
      indexCols: CSV_FILE.COLS_TOWN_ID,
      stmt: db.prepare('UPDATE "town" SET "代表点_経度" = ?, "代表点_緯度" = ? WHERE "code" = ? AND "town_id" = ?'),
    },
```

すると「2」という数字は見えてきませんが、「COLS_TOWN_ID」という名前から「town に対する id なのだろう」と想像が付きます。
`db.prepare('UPDATE "town" SET "代表点_経度" = ?, "代表点_緯度" = ? WHERE "code" = ? AND "town_id" = ?')` にある`town_id` というところに入ってくるのかもしれない、と予測を付けることができます。

--------

もし、対象とするCSVファイルのカラム順が変更になったとして、読み取る対象が `2` から `3` になったとしましょう。
`COLS_TOWN_ID = 2` としてあれば、変更は簡単ですね。
でももしハードコーディングしてあったら、この「2」を変更するべきなのか、してはいけないのか、コードを読まないと分かりません。

```
    'town_pos': {
      indexCols: 2,
      stmt: db.prepare('UPDATE "town" SET "代表点_経度" = ?, "代表点_緯度" = ? WHERE "code" = ? AND "town_id" = ?'),
    },
```

--------
マジックナンバーをハードコーディングすることの危険性を理解していただけましたかね。

マジックナンバーをハードコーディングして、その値が変更になったときにテキストエディタで置換して動かなくなった、なんて経験を私は若い頃に何度もしています。それを見つけ出すのに数時間かかることもありますし、あとから時限爆弾のように不具合を起こすこともあります。

「**数字をハードコーディングする**」、ということは、「**そのソフトウェアに爆弾を埋め込むということに等しい**」、ということをご理解ください。

もし納得いただけないなら、こちらの記事を読んでください。
[明日もう一度来て下さい。本当のマジックナンバーを見せてあげますよ](https://zenn.dev/koduki/articles/95d4ced70db0ab)

---------

あと `MATCH_LEVEL` に採用した英語変数名は、
https://github.com/digital-go-jp/abr-geocoder/blob/ae3e4e62d4ef5924085f58f677f208267f2fb318/src/domain/match-level.ts#L24-L42

Google Maps Geocoding API の component types をベースにして決めました。 
https://developers.google.com/maps/documentation/geocoding/requests-geocoding#Types

世界中で使われているAPIで、多数の英単語候補から分かりやすい単語を選んでいるはずですので、私の下手な英語よりも一般的なはずです。

`RESIDENTIAL_BLOCK`, `RESIDENTIAL_DETAIL` については、`neighborhood` にしようかと思いましたが、元データのファイルが `rsdt_****` （residential の r,s,d,t）から来ているようだったので、敢えて「RESIDENTIAL_BLOCK」と「RESIDENTIAL_DETAIL」にしています。

2024-01-20 23:10 UTC, maskatsum commented
テスト結果の件、ありがとうございます。データの取得方法のSQLが提示されているので、再現性があり、ありがたいです。

追加検証はしてみますが、たぶん指摘いただいているポイントが、今回のPRと合っていません。

v1.0からv1.1 に全コードを書き換える際に、「v1.0のロジックをキープしてほしい」ということでしたので、そのようにしています。
その結果として、ジオコーディングは「step1 - step8」に分かれます。

「マッチングレベル2」を「マッチングレベル3」に向上させる部分は、小字は関係してきません。
むしろ「大字」の部分が関係してきていて、そのコードは「v1.0からの引き継いだロジックの部分に含まれています」。

今回の調査をする上で、この問題にも気づきました。
検討の結果、これを改善させるには、

2024-01-20 23:27 UTC, maskatsum commented
追加検証の必要が出てきたので、一旦 draft に戻します。

2024-01-20 23:31 UTC, maskatsum commented
README.md に matchLevel = 4 が残っていたので、削除。

2024-01-20 23:32 UTC, maskatsum commented
<!-- Jest Coverage Comment: lint_and_build -->
## Coverage Summary

| Lines | Statements | Branches | Functions |
| --- | --- | --- | --- |
| <a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/README.md"><img alt="Coverage: 82%" src="https://img.shields.io/badge/Coverage-82%25-green.svg" /></a><br/> | 82.5% (1457/1766) | 60.45% (185/306) | 78.98% (218/276) |


## JUnit

| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 133 | 0 :zzz: | 0 :x: | 0 :fire: | 8.701s :stopwatch: |


<details><summary>Coverage Details (<b>82%</b>)</summary><table><tr><th>File</th><th>% Stmts</th><th>% Branch</th><th>% Funcs</th><th>% Lines</th><th>Uncovered Line #s</th></tr><tbody><tr><td><b>All files</b></td><td><b>82.5</b></td><td><b>60.45</b></td><td><b>78.98</b></td><td><b>82.14</b></td><td>&nbsp;</td></tr><tr><td>cli</td><td>95.29</td><td>79.16</td><td>100</td><td>95.12</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/cli/cli.ts">cli.ts</a></td><td>95.29</td><td>79.16</td><td>100</td><td>95.12</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/cli/cli.ts#L263">263</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/cli/cli.ts#L281">281</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/cli/cli.ts#L309">309</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/cli/cli.ts#L315">315</a></td></tr><tr><td>controller/download</td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/download/download-dataset-result.ts">download-dataset-result.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/download/download-dataset.ts">download-dataset.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>controller/download/process</td><td>75.6</td><td>73.91</td><td>62.5</td><td>74.57</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/download/process/download-process.ts">download-process.ts</a></td><td>23.52</td><td>100</td><td>0</td><td>18.75</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/download/process/download-process.ts#L46-L77">46&ndash;77</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/download/process/extract-dataset-process.ts">extract-dataset-process.ts</a></td><td>50</td><td>100</td><td>0</td><td>45.45</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/download/process/extract-dataset-process.ts#L45-L60">45&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/download/process/load-dataset-history.ts">load-dataset-history.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/download/process/load-dataset-process.ts">load-dataset-process.ts</a></td><td>87.2</td><td>73.91</td><td>88.88</td><td>86.9</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/download/process/load-dataset-process.ts#L77">77</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/download/process/load-dataset-process.ts#L100-L102">100&ndash;102</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/download/process/load-dataset-process.ts#L131-L132">131&ndash;132</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/download/process/load-dataset-process.ts#L155-L158">155&ndash;158</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/download/process/load-dataset-process.ts#L216">216</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/download/process/load-dataset-process.ts#L226">226</a></td></tr><tr><td>controller/geocode</td><td>90.25</td><td>64.28</td><td>78.94</td><td>90.18</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/geocode/geocode.ts">geocode.ts</a></td><td>81.08</td><td>41.66</td><td>100</td><td>80.55</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/geocode/geocode.ts#L87-L106">87&ndash;106</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/geocode/geocode.ts#L116">116</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/geocode/step1-transform.ts">step1-transform.ts</a></td><td>95.23</td><td>100</td><td>85.71</td><td>95.23</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/geocode/step1-transform.ts#L105">105</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/geocode/step2-transform.ts">step2-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/geocode/step3-transform.ts">step3-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/geocode/step3a-transform.ts">step3a-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/geocode/step3b-transform.ts">step3b-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/geocode/step3final-transform.ts">step3final-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/geocode/step4-transform.ts">step4-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/2cc4de15e0575c69c3335debe97c0ea3bb0646d6/./src/controller/geocode/step5-transform.ts">step5-transform.ts</a></td><td>86.48</td><td>100</td><td>54.54</td><td>86.48</td><td><a  [...]

2024-01-22 04:19 UTC, maskatsum commented
@koswatana さんとface to faceで協議の結果、町字までが正しく判定できていないケースがあるのは、本PRではカバーしないことにします（予想されるロジックの変更が大きいので、v2.0の開発に悪影響を及ぼす可能性が大きいため）。

町字までが正しく判定できていないケースがある　については、別PRを作って継続開発を行います。

マジックナンバーについては、理解頂けました。ただし定数名については、将来的に変更される可能性があります。

2024-01-22 05:40 UTC, koswatana requested changes

2024-01-22 05:43 UTC, maskatsum commented on src/domain/geocode-result.ts
> +      }
あれ、残っているな。。。

2024-01-22 05:48 UTC, maskatsum commented on src/domain/geocode-result.ts
> +      }
すみません。ローカルでコミットがちゃんとできてなかったです。

2024-01-22 05:51 UTC, maskatsum commented
<!-- Jest Coverage Comment: lint_and_build -->
## Coverage Summary

| Lines | Statements | Branches | Functions |
| --- | --- | --- | --- |
| <a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/README.md"><img alt="Coverage: 82%" src="https://img.shields.io/badge/Coverage-82%25-green.svg" /></a><br/> | 82.46% (1453/1762) | 60.06% (182/303) | 78.98% (218/276) |


## JUnit

| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 132 | 0 :zzz: | 0 :x: | 0 :fire: | 8.628s :stopwatch: |


<details><summary>Coverage Details (<b>82%</b>)</summary><table><tr><th>File</th><th>% Stmts</th><th>% Branch</th><th>% Funcs</th><th>% Lines</th><th>Uncovered Line #s</th></tr><tbody><tr><td><b>All files</b></td><td><b>82.46</b></td><td><b>60.06</b></td><td><b>78.98</b></td><td><b>82.09</b></td><td>&nbsp;</td></tr><tr><td>cli</td><td>95.29</td><td>79.16</td><td>100</td><td>95.12</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/cli/cli.ts">cli.ts</a></td><td>95.29</td><td>79.16</td><td>100</td><td>95.12</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/cli/cli.ts#L263">263</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/cli/cli.ts#L281">281</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/cli/cli.ts#L309">309</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/cli/cli.ts#L315">315</a></td></tr><tr><td>controller/download</td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/download/download-dataset-result.ts">download-dataset-result.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/download/download-dataset.ts">download-dataset.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>controller/download/process</td><td>75.6</td><td>73.91</td><td>62.5</td><td>74.57</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/download/process/download-process.ts">download-process.ts</a></td><td>23.52</td><td>100</td><td>0</td><td>18.75</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/download/process/download-process.ts#L46-L77">46&ndash;77</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/download/process/extract-dataset-process.ts">extract-dataset-process.ts</a></td><td>50</td><td>100</td><td>0</td><td>45.45</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/download/process/extract-dataset-process.ts#L45-L60">45&ndash;60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/download/process/load-dataset-history.ts">load-dataset-history.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/download/process/load-dataset-process.ts">load-dataset-process.ts</a></td><td>87.2</td><td>73.91</td><td>88.88</td><td>86.9</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/download/process/load-dataset-process.ts#L77">77</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/download/process/load-dataset-process.ts#L100-L102">100&ndash;102</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/download/process/load-dataset-process.ts#L131-L132">131&ndash;132</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/download/process/load-dataset-process.ts#L155-L158">155&ndash;158</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/download/process/load-dataset-process.ts#L216">216</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/download/process/load-dataset-process.ts#L226">226</a></td></tr><tr><td>controller/geocode</td><td>90.25</td><td>64.28</td><td>78.94</td><td>90.18</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/geocode/geocode.ts">geocode.ts</a></td><td>81.08</td><td>41.66</td><td>100</td><td>80.55</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/geocode/geocode.ts#L87-L106">87&ndash;106</a>, <a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/geocode/geocode.ts#L116">116</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/geocode/step1-transform.ts">step1-transform.ts</a></td><td>95.23</td><td>100</td><td>85.71</td><td>95.23</td><td><a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/geocode/step1-transform.ts#L105">105</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/geocode/step2-transform.ts">step2-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/geocode/step3-transform.ts">step3-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/geocode/step3a-transform.ts">step3a-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/geocode/step3b-transform.ts">step3b-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/geocode/step3final-transform.ts">step3final-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/geocode/step4-transform.ts">step4-transform.ts</a></td><td>100</td><td>100</td><td>100</td><td>100</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/digital-go-jp/abr-geocoder/blob/775d159113b6848e79ebd2c28a7d8429ffe0b6ce/./src/controller/geocode/step5-transform.ts">step5-transform.ts</a></td><td>86.48</td><td>100</td><td>54.54</td><td>86.48</td><td>< [...]

2024-01-24 04:41 UTC, koswatana approved these changes

2024-01-24 05:18 UTC, merged